import {
  pgTable,
  text,
  timestamp,
  integer,
  jsonb,
  index,
  primaryKey,
} from "drizzle-orm/pg-core";

/**
 * Phase C Wave C2 / Story 2 — Entity store.
 *
 * `entities` is the canonical table — one row per (canonical-name, type)
 * pair. `canonical_name` is the lowercased + diacritic-normalized form
 * used for dedup ("Anna Müller" and "anna mueller" collapse to a single
 * row). `display_name` keeps the first observed cased form for UI; later
 * observed variants accumulate in the `aliases` array.
 *
 * `entity_mentions` is the per-(entity, note) edge table. The composite
 * PK keeps the relation idempotent across re-runs of the entity-extraction
 * sleep-pass — the second observation of the same (entity, note) pair
 * does NOT create a duplicate row (we ON CONFLICT DO NOTHING upserts in
 * `entities/index.ts`), only the `mention_count` on the entity row is
 * incremented. `context` carries a ~200-char snippet from the surrounding
 * text so the UI can show "where did we see this?" without re-reading the
 * note body.
 *
 * Mention-count semantics: `entities.mention_count` is total mentions
 * across all notes, NOT distinct notes. `entity_mentions` row count gives
 * distinct-note count. Both are useful, kept separate by design.
 */
export const entities = pgTable(
  "entities",
  {
    /** ULID, generated by the upsert path before INSERT. */
    id: text("id").primaryKey(),
    /** Lowercased + diacritic-stripped + whitespace-collapsed form. */
    canonicalName: text("canonical_name").notNull(),
    /** First observed cased form — what the UI shows by default. */
    displayName: text("display_name").notNull(),
    /** One of: "person" | "organization" | "location" | "concept" | "date" | "event". */
    type: text("type").notNull(),
    /** Display-name variants accumulated across notes. */
    aliases: text("aliases").array().notNull().default([]),
    firstSeen: timestamp("first_seen", { withTimezone: true })
      .notNull()
      .defaultNow(),
    lastSeen: timestamp("last_seen", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** Total mentions across all notes (NOT distinct notes). */
    mentionCount: integer("mention_count").notNull().default(0),
    /** Free-form per-entity payload (provenance, scores, …). JSONB-flexible. */
    metadata: jsonb("metadata"),
  },
  (t) => ({
    canonicalIdx: index("idx_entities_canonical").on(t.canonicalName),
    typeIdx: index("idx_entities_type").on(t.type),
  }),
);

export type EntityRow = typeof entities.$inferSelect;
export type NewEntityRow = typeof entities.$inferInsert;

export const entityMentions = pgTable(
  "entity_mentions",
  {
    entityId: text("entity_id").notNull(),
    noteId: text("note_id").notNull(),
    observedAt: timestamp("observed_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** "0..1" stored as string to avoid float-rounding for UI display. */
    confidence: text("confidence"),
    /** ~200-char text snippet around the mention. */
    context: text("context"),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.entityId, t.noteId] }),
    noteIdx: index("idx_entity_mentions_note").on(t.noteId),
    entityIdx: index("idx_entity_mentions_entity").on(t.entityId),
  }),
);

export type EntityMentionRow = typeof entityMentions.$inferSelect;
export type NewEntityMentionRow = typeof entityMentions.$inferInsert;

/** Closed list of entity types — keep in lockstep with the extraction prompt. */
export const ENTITY_TYPES = [
  "person",
  "organization",
  "location",
  "concept",
  "date",
  "event",
] as const;
export type EntityType = (typeof ENTITY_TYPES)[number];

export function isEntityType(value: string): value is EntityType {
  return (ENTITY_TYPES as readonly string[]).includes(value);
}
