import {
  pgTable,
  text,
  timestamp,
  jsonb,
  index,
} from "drizzle-orm/pg-core";

/**
 * Phase C Wave C1 / Story 3 — Karpathy-Lint findings table.
 *
 * Persists the output of the daily lint sleep-pass (`karpathy-lint`). Each
 * row is one finding produced by one of the five lint heuristics:
 *
 *   - `orphan`        — note with no incoming links, no tags, untouched for
 *                       30+ days (low-cost, no LLM)
 *   - `contradiction` — two notes with overlapping tags whose bodies the
 *                       `lint`-role LLM judges as inconsistent (capped at
 *                       MAX_CONTRADICTIONS_PER_RUN per invocation)
 *   - `missing_link`  — `[[X]]` referenced from MIN_CROSS_REF_COUNT+ notes
 *                       where no note titled / id'd `X` exists
 *   - `schema_drift`  — frontmatter that fails its type's JSON-schema (this
 *                       runs even on already-committed notes; the pre-commit
 *                       hook can drift if schemas evolve post-write)
 *   - `duplicate`     — semantic neighbours with cosine-similarity >0.92 on
 *                       Tier 2 (title + body chunks)
 *
 * The pass writes findings as `status = "open"`; the user-facing review UI
 * then walks them through `acknowledged` → `fixed` (or `dismissed`).
 * Duplicate-suppression is done at write-time by the pass itself: if a
 * `kind + noteIds + status="open"` row already exists, the new finding is
 * skipped. We deliberately do NOT enforce that as a DB unique-constraint
 * because `noteIds` is an array and Postgres index semantics over array
 * equality are subtle — the TS-side check is simpler and accurate enough.
 *
 * Indexes:
 *   - `idx_lint_status` — the review queue lists `status = 'open'` rows
 *   - `idx_lint_kind`   — per-kind dashboards (orphan-count etc.) read this
 */
export const lintFindings = pgTable(
  "lint_findings",
  {
    /** ULID, generated by the pass before insert. */
    id: text("id").primaryKey(),
    /** One of: "orphan" | "contradiction" | "missing_link" | "schema_drift" | "duplicate". */
    kind: text("kind").notNull(),
    /**
     * Affected notes — 1 entry for orphan/schema_drift, 2 for contradiction/
     * duplicate, N for missing_link (all referring sources).
     */
    noteIds: text("note_ids").array().notNull(),
    /** "info" | "warning" | "error" — enforced in TS. */
    severity: text("severity").notNull(),
    /** Human-readable summary surfaced in the review UI. */
    message: text("message").notNull(),
    /**
     * Kind-specific structured payload (similarity score, missing target,
     * Ajv errors, …). JSONB so we never need a schema migration to add
     * new evidence fields per kind.
     */
    evidence: jsonb("evidence"),
    /** "open" | "acknowledged" | "fixed" | "dismissed". Enforced in TS. */
    status: text("status").notNull().default("open"),
    detectedAt: timestamp("detected_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** Set when the user transitions to a terminal status. */
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  },
  (table) => ({
    statusIdx: index("idx_lint_status").on(table.status),
    kindIdx: index("idx_lint_kind").on(table.kind),
  }),
);

export type LintFindingRow = typeof lintFindings.$inferSelect;
export type NewLintFindingRow = typeof lintFindings.$inferInsert;

/** Lint heuristic kinds — keep in lockstep with `lintPass`. */
export const LINT_KINDS = [
  "orphan",
  "contradiction",
  "missing_link",
  "schema_drift",
  "duplicate",
] as const;
export type LintKind = (typeof LINT_KINDS)[number];

export const LINT_SEVERITIES = ["info", "warning", "error"] as const;
export type LintSeverity = (typeof LINT_SEVERITIES)[number];

export const LINT_STATUSES = [
  "open",
  "acknowledged",
  "fixed",
  "dismissed",
] as const;
export type LintStatus = (typeof LINT_STATUSES)[number];

export function isLintKind(value: string): value is LintKind {
  return (LINT_KINDS as readonly string[]).includes(value);
}

export function isLintStatus(value: string): value is LintStatus {
  return (LINT_STATUSES as readonly string[]).includes(value);
}
