import { pgTable, text, timestamp, jsonb, index } from "drizzle-orm/pg-core";

/**
 * Phase A Wave A1 / Story 3 — Retrieval-Trace-Log.
 *
 * Multiple-Trace-Theory (Nadel & Moscovitch 1997): every retrieval is itself
 * a write-event. We append one row per note-access (search, wikilink,
 * cmd-k, cmd-o, hover, embed, api, mcp) — over time this builds "many
 * indices into the same content" and feeds the future sleep-agent +
 * recency-reset loop.
 *
 * Append-only, no FK on `note_id` (vault notes are .md files owned by
 * gitService; we never want a stale trace to block a rebase).
 *
 * Indexes:
 *   - `idx_retrieval_traces_note`    — fast lookup of all accesses per note
 *   - `idx_retrieval_traces_session` — co-retrieval pair aggregation (partial)
 *   - `idx_retrieval_traces_time`    — time-window scans for retrievalCounts
 */
export const retrievalTraces = pgTable(
  "retrieval_traces",
  {
    /** ULID — generated by `logRetrieval`, not the DB. */
    id: text("id").primaryKey(),
    /** Frontmatter ULID of the accessed note (NOT the path-id). */
    noteId: text("note_id").notNull(),
    /** Defaults to NOW() at the DB layer; callers don't pass a clock. */
    accessedAt: timestamp("accessed_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** Nullable: not every retrieval has a user session (background jobs). */
    sessionId: text("session_id"),
    /** Nullable: pre-login or service-account access. */
    userId: text("user_id"),
    /**
     * Closed list, enforced in the TS layer (`RetrievalSource`):
     * "search" | "wikilink" | "cmd-k" | "cmd-o" | "hover" | "embed"
     * | "api" | "mcp".
     */
    source: text("source").notNull(),
    /** The query string, if the retrieval came from a search-like surface. */
    query: text("query"),
    /** Previous open notes in same session (small, cap ~5). */
    preceding: text("preceding").array(),
    /** Extensible bag — typed `Record<string, unknown>` at the TS boundary. */
    context: jsonb("context"),
  },
  (table) => ({
    noteIdx: index("idx_retrieval_traces_note").on(table.noteId),
    sessionIdx: index("idx_retrieval_traces_session").on(table.sessionId),
    timeIdx: index("idx_retrieval_traces_time").on(table.accessedAt),
  }),
);

export type RetrievalTrace = typeof retrievalTraces.$inferSelect;
export type NewRetrievalTrace = typeof retrievalTraces.$inferInsert;
