import {
  pgTable,
  text,
  integer,
  timestamp,
  jsonb,
  index,
} from "drizzle-orm/pg-core";

/**
 * Phase A Wave A2 / Story 7 — Sleep-Agent run log.
 *
 * Walking-skeleton table — one row per sleep-agent run (idle / nightly /
 * manual). Story 7 ships with a single pass (`importance-recompute`),
 * later stories append re-embed, multi-trace consolidation, synaptic
 * pruning, topic-synthesis, lint, … without altering the schema. The
 * pass results all land in `pass_stats` as a JSONB bag, keyed by pass
 * name.
 *
 * Indexes:
 *   - `idx_sleep_agent_status`  — quick check whether anything is `running`.
 *   - `idx_sleep_agent_started` — recent-runs feed for the admin UI.
 */
export const sleepAgentRuns = pgTable(
  "sleep_agent_runs",
  {
    /** ULID, generated by the SleepAgent before the row is inserted. */
    id: text("id").primaryKey(),
    /** "nrem" | "rem" | "lint" | "dream" | "manual" — enforced in TS. */
    phase: text("phase").notNull(),
    /** "idle" | "nightly" | "manual" — enforced in TS. */
    trigger: text("trigger").notNull(),
    /**
     * "pending" | "running" | "completed" | "failed" | "cancelled".
     * Enforced in TS via `SleepStatus`.
     */
    status: text("status").notNull(),
    /** Defaults to NOW() at the DB layer; callers don't pass a clock. */
    startedAt: timestamp("started_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** Set on terminal status transition (completed/failed/cancelled). */
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    /** Pass names that succeeded for this run, e.g. ["importance-recompute"]. */
    passesCompleted: text("passes_completed")
      .array()
      .notNull()
      .default([]),
    /**
     * Per-pass stats bag — `{ "importance-recompute": { processed, errors } }`.
     * Typed as `Record<string, unknown>` at the TS boundary; the SleepRun
     * record narrows individual pass payloads.
     */
    passStats: jsonb("pass_stats").notNull().default({}),
    /** Error message on `status = "failed"`. Null otherwise. */
    errorMessage: text("error_message"),
    /** Sum of `processed` counts across all passes that succeeded. */
    notesProcessed: integer("notes_processed").notNull().default(0),
  },
  (table) => ({
    statusIdx: index("idx_sleep_agent_status").on(table.status),
    startedIdx: index("idx_sleep_agent_started").on(table.startedAt),
  }),
);

export type SleepAgentRunRow = typeof sleepAgentRuns.$inferSelect;
export type NewSleepAgentRunRow = typeof sleepAgentRuns.$inferInsert;
