import {
  pgTable,
  text,
  timestamp,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/**
 * Phase C Wave C2 / Story 1 — Bi-Temporal Edges (Graphiti pattern).
 *
 * Graphiti (Zep, arXiv:2501.13956, Jan 2025) introduces bi-temporal edges as
 * the foundation of a temporally-aware knowledge graph. Each edge carries
 * FOUR timestamps:
 *
 *   - `t_created`  — when the edge was inserted into the system
 *   - `t_expired`  — when the row was tombstoned in the system (null = active)
 *   - `t_valid`    — when the asserted fact began holding in the real world
 *   - `t_invalid`  — when the asserted fact stopped holding (null = still valid)
 *
 * The crucial property: when a later note contradicts an earlier one, the
 * older edge is NOT deleted — `t_invalid` is set. Historical queries at any
 * past timestamp T return the edges that were valid at T. This is "time-
 * travelling graph queries" without rewriting history.
 *
 * Concrete example:
 *   Note A (2024): "Anna works at Firma X" → temporal_edge A → Anna with
 *     `t_valid = 2024, t_invalid = NULL`.
 *   Note B (2026): "Anna works at Firma Y" → caller invalidates the A→Anna
 *     edge (`t_invalid = 2026, invalidated_by = <Note B id>`) and inserts a
 *     new B → Anna edge with `t_valid = 2026, t_invalid = NULL`.
 *   Both rows persist; a point-in-time query at 2025 returns A→Anna only.
 *
 * Why this lives in a PARALLEL table to `edge_weights`:
 *   - `edge_weights` tracks SYNAPTIC STRENGTH (Tononi-Cirelli homeostasis) —
 *     a single weight per directed pair, recomputed every NREM run.
 *   - `temporal_edges` tracks ASSERTION HISTORY — every claim a note has ever
 *     made about a target, with full invalidation chains. Multiple rows per
 *     (from, to) pair are normal and expected.
 *   They serve different use-cases, mix them at the call site only.
 *
 * Indexes:
 *   - `idx_temporal_edges_from`   — "all edges out of note X" (graph traversal)
 *   - `idx_temporal_edges_to`     — "all edges into target Y"
 *   - `idx_temporal_edges_active` — PARTIAL index on rows with `t_invalid IS
 *                                   NULL`. The hot path for retrieval lives
 *                                   here: 99% of queries want active edges
 *                                   only and the index size stays bounded
 *                                   even as historical rows accumulate.
 *   - `idx_temporal_edges_valid`  — sleep-pass stale-detection scans the
 *                                   oldest active edges first.
 */
export const temporalEdges = pgTable(
  "temporal_edges",
  {
    /** ULID, generated by the caller before insert. */
    id: text("id").primaryKey(),
    fromNoteId: text("from_note_id").notNull(),
    toNoteId: text("to_note_id").notNull(),
    /**
     * Free-text kind tag. We deliberately do NOT enforce this as a Postgres
     * enum: the kind taxonomy is expected to grow (entity_mention,
     * asserts_fact, …) and an enum migration per new kind is more pain than
     * the type-safety is worth. Validation lives in TS via `EDGE_KINDS`.
     */
    edgeKind: text("edge_kind").notNull(),

    // ── Bi-temporal columns ────────────────────────────────────────────
    /** Wall-clock at which the row was inserted into this system. */
    tCreated: timestamp("t_created", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** Wall-clock at which the row was tombstoned in this system. NULL = active. */
    tExpired: timestamp("t_expired", { withTimezone: true }),
    /** Real-world time at which the asserted fact began holding. */
    tValid: timestamp("t_valid", { withTimezone: true }).notNull(),
    /** Real-world time at which the asserted fact stopped holding. NULL = still valid. */
    tInvalid: timestamp("t_invalid", { withTimezone: true }),

    // ── Source attribution ─────────────────────────────────────────────
    /** Note that asserted this edge. NULL when inferred by the system. */
    sourceNoteId: text("source_note_id"),
    /** Note that invalidated this edge. NULL while edge is still valid. */
    invalidatedBy: text("invalidated_by"),

    // ── Payload ────────────────────────────────────────────────────────
    /** Optional natural-language verbalization of the asserted fact. */
    factText: text("fact_text"),
    /** Stored as text "0.0".."1.0" so callers can pick their own precision. */
    confidence: text("confidence"),
    /** Free-form per-edge metadata, evolves without a migration. */
    metadata: jsonb("metadata"),
  },
  (t) => ({
    fromIdx: index("idx_temporal_edges_from").on(t.fromNoteId),
    toIdx: index("idx_temporal_edges_to").on(t.toNoteId),
    /**
     * PARTIAL index: only rows where the edge is still valid. The hot
     * retrieval path is `activeEdgesFrom` which always filters on
     * `t_invalid IS NULL`. Without the partial filter the index size grows
     * unbounded with historical rows; with it, the index stays ~ O(active
     * edge count) regardless of how much history has accumulated.
     */
    activeIdx: index("idx_temporal_edges_active")
      .on(t.fromNoteId, t.toNoteId)
      .where(sql`${t.tInvalid} IS NULL`),
    /** Used by the bi-temporal-validation sleep-pass to scan oldest first. */
    validIdx: index("idx_temporal_edges_valid").on(t.tValid),
  }),
);

export type TemporalEdgeRow = typeof temporalEdges.$inferSelect;
export type NewTemporalEdgeRow = typeof temporalEdges.$inferInsert;

/**
 * Open-text on the column, but the TS surface uses a closed union for
 * compile-time discipline. Add a new kind here when needed — no migration
 * required.
 */
export const EDGE_KINDS = [
  "wikilink",
  "mdlink",
  "alias",
  "entity_mention",
  "asserts_fact",
] as const;
export type TemporalEdgeKind = (typeof EDGE_KINDS)[number];

export function isTemporalEdgeKind(value: string): value is TemporalEdgeKind {
  return (EDGE_KINDS as readonly string[]).includes(value);
}
